# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 449b2f488c876b6f63ea1c764585a8b794c1ff24f1afd685162ea800211f7bf9afa807c9bfa60b0acf925a9d33712e3c25e0a92e061fc819468b7b93a071c17a

test:
  secret_key_base: 2a60625df438de458a5f75782c5d0e930d10d19faa3eeb3ddde222efd7554f1c284d8a7b4c1439b3e50917d61415847459d8c78ac4109ae0cbd46f0488f84588

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
